### ISSUE TITLE
Publish to NuGet.org

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/xliff-tasks#422]
For easier consumption, the package needs to be published to NuGet.org

**Comment by riarenas** [comment]
@Youssef1313 This package is publicly available from this azure artifacts feed: https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json so feel free to stick that to your restore sources. 

We currently have no plans to make this package available in nuget.org because right now it's very tightly integrated to our engineering systems to build the .net product.

**Comment by Youssef1313** [comment]
@riarenas While the package is indeed publicly available, it cannot be used easily as no one will want to use mixed feeds to avoid dependency confusion vulnerability. But if it should only be used throughout the .NET organization, feel free to close.

**Comment by GertjanBrouwer** [comment]
Just want to mention here that this package is required to build Xamarin.Forms. 
However, it can't be found without manually adding the above link. 
This is not a desirable situation imo.
