### ISSUE TITLE
Generated satellite assemblies contain always debug information

### ISSUE THREAD

**Issue by kinex** [dotnet/xliff-tasks#60]
My app fails WACK (=not accepted to Windows Store). For details please see this [Stack Overflow question](https://stackoverflow.com/questions/51261637/using-microsoft-codeanalysis-nuget-package-causes-wack-to-fail).

After investigating this issue for several days I have high doubts that xliff-tasks must be the root cause for the WACK issues "The binary *.resources.dll is built in debug mode".

I tested this by building [Microsoft.Build.csproj](https://github.com/Microsoft/msbuild/tree/master/src/Build/Microsoft.Build.csproj) in Release-configuration. Generated satellite assemblies contain always debug information, even if I build the project with Release-configuration. I have verified this using the [Assembly Information](https://archive.codeplex.com/?p=assemblyinformation) tool.

At least I am not aware of any project setting (other than project configuration Release/Debug) which could effect the generated satellite assemblies configuration. So my conclusion is that the bug is not directly in the Microsoft.Build.csproj project but in the NuGet package "XliffTasks" it uses.

**Comment by tmeschter** [comment]
@kinex XliffTasks does not handle generating the *.resources.dll files itself. Rather, at build time it translates the .xlf files back to .resx/.vsct/.txt/etc. with the appropriate locale, and the regular build processes take it from there. So the problem is likely elsewhere.

@nguerrera I suspect the [CoreGenerateSatelliteAssemblies](https://github.com/dotnet/sdk/blob/63100e9401a02af7e1b1ec6f44be586312c1da96/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets#L442) target in [dotnet/sdk](https://github.com/dotnet/sdk) is not properly taking Debug vs. Release into account when it calls the `Csc` task, and we're just getting defaulted into debug bits.

**Comment by kinex** [comment]
@tmeschter Ok thanks for the info. The good news is that my app should not be rejected from Store because of this issue. I found this article after reporting this issue:  [Windows Desktop Bridge app tests](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/windows-desktop-bridge-app-tests). According to it "Debug configuration test" is currently only "Optional test". But I guess that could change in future so @nguerrera I hope you will fix this. A possibly related issue is that WACK reports also several .NET framework libraries to contain debug information (e.g. _The binary System.Collections.dll is built in debug mode._). But for now I can ignore that issue too.

I will close this issue as it was reported in wrong project.
